### ISSUE TITLE
Ram usage while using Todds 

### ISSUE THREAD

**Issue by cylian914** [joseasoler/todds#18]
For some reason Todds keep using more and more ram,  and after like 5min it crashes Wayland cause there is not enought ram available (no swap)

I didn't look at how Todds work but I assume it inport game asset into memory, are they removed after ?
Note: i only use the one include in rimsort

**Comment by joseasoler** [comment]
todds RAM usage is fairly low. There is a limit to the maximum number of images that can be loaded in memory at the same time, and they get cleaned up as soon as they are written to disk.

To check if the issue is in todds or in RimSort, you could download the standalone todds version from here: https://github.com/joseasoler/todds/releases/tag/0.2.0

And then follow this tutorial to encode images using just todds: https://github.com/joseasoler/todds/wiki/Example:-RimWorld

I would recommend replacing `-on` with `-o` to ensure that todds will overwrite any image that was left corrupted after the computer ran out of RAM.

**Comment by cylian914** [comment]
After a system update my todds's ram issue seem to be fix, it look like it was link to xdg-desktop-portal-kde that would crash after a high ram usage and high use for the graphic card for more then 5 minutes

**Comment by joseasoler** [comment]
Thank you for letting me know, I am happy that the issue is fixed :)
